[[plugins]]
repo = 'tyru/open-browser.vim'
rev = '39e80649c739151673373bbaf3a56d126531467b'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
if = '!g:vimrc.is_kaoriya && !g:vimrc.is_windows'

[[plugins]]
repo = 'LeafCage/foldCC'

[[plugins]]
repo = 'kana/vim-submode'

[[plugins]]
repo = 'osyo-manga/vim-anzu'

[[plugins]]
repo = 'deris/vim-shot-f'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'aiya000/aho-bakaup.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
rev = 'b7c241fb5737c50bf09cf1e26298492c3fc0457a'
[[plugins]]
repo = 'kana/vim-textobj-user'


[[plugins]]
repo = 'kana/vim-textobj-indent'
depends = 'vim-textobj-user'

[[plugins]]
repo = 'osyo-manga/vim-textobj-from_regexp'
depends = 'vim-textobj-user'

[[plugins]]
repo = 'whatyouhide/vim-textobj-xmlattr'
depends = 'vim-textobj-user'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'thinca/vim-visualstar'

[[plugins]]
repo = 'vim-jp/autofmt'

[[plugins]]
repo = 'dense-analysis/ale'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'kana/vim-textobj-jabraces'

[[plugins]]
repo = 'aiya000/lucariox.vim'

[[plugins]]
repo = 'machakann/vim-highlightedyank'

[[plugins]]
repo = 'andymass/vim-matchup'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'

[[plugins]]  # NOTE: This plugin cannot be lazy because (maybe) global functions of ./plugin is not cached.
repo = 'tyru/sync-term-cwd.vim'

[[plugins]]
repo = 'kana/vim-repeat'

[[plugins]]
repo = 'chip/vim-fat-finger'

[[plugins]]
repo = 'itchyny/vim-cursorword'

[[plugins]]
repo = 'justinmk/vim-dirvish'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
depends = 'async.vim'

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'rhysd/vim-lsp-ale'

[[plugins]]
repo = 'aiya000/vim-fakeclip'
if = 'g:vimrc.is_wsl || g:vimrc.is_wsl2'

[[plugins]]
repo = 'vim-scripts/Align'

[[plugins]]
repo = 'cohama/lexima.vim'
rev = '36781e59099b9b46eed564283b95938f90cd852d'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'vim-denops/denops-helloworld.vim'

[[plugins]]
repo = 'Shougo/ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-ui-ff'

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'

[[plugins]]
repo = 'Shougo/ddu-kind-file'

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'

[[plugins]]
repo = 'Shougo/ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-ui-native'

[[plugins]]
repo = 'Shougo/ddc-source-around'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'

[[plugins]]
repo = 'shun/ddc-source-vim-lsp'

[[plugins]]
repo = 'LumaKernel/ddc-source-file'

[[plugins]]
repo = 'shun/ddu-source-buffer'

[[plugins]]
repo = 'Shougo/ddu-source-file_old'

[[plugins]]
repo = 'tani/ddc-fuzzy'

[[plugins]]
repo = 'matsui54/ddu-source-help'

[[plugins]]
repo = 'shun/ddu-source-rg'

[[plugins]]
repo = 'matsui54/ddc-buffer'

[[plugins]]
repo = 'lambdalisue/kensaku.vim'

[[plugins]]
repo = 'lambdalisue/kensaku-search.vim'

[[plugins]]
repo = 'Shougo/ddu-source-line'

[[plugins]]
repo = 'lambdalisue/fern.vim'
