[[plugins]]
repo = 'tyru/open-browser.vim'
rev  = '39e80649c739151673373bbaf3a56d126531467b'

[[plugins]]
repo  = 'Shougo/vimproc.vim'
rev   = '25cb83f24edec4aec1e9f1329302235e7a7a7fe0'
build = 'make'
if    = '!(g:vimrc["is_kaoriya"] && g:vimrc["is_windows"])'

[[plugins]]
repo = 'LeafCage/foldCC'

[[plugins]]
repo = 'kana/vim-submode'

[[plugins]]
repo = 'osyo-manga/vim-anzu'

[[plugins]]
repo = 'h1mesuke/vim-alignta'

[[plugins]]
repo = 'deris/vim-shot-f'

[[plugins]]
repo = 'tyru/vim-altercmd'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'aiya000/aho-bakaup.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
rev  = 'c9b41fe9b8cca4b6a11cc0cbe71eecb94fa8a30f'

[[plugins]]
repo    = 'kana/vim-textobj-indent'
depends = 'vim-textobj-user'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
rev  = 'fee9301bfa8d52efc38d314b17bf89c39c22015d'

[[plugins]]
repo    = 'osyo-manga/vim-textobj-from_regexp'
depends = 'vim-textobj-user'

[[plugins]]
repo    = 'whatyouhide/vim-textobj-xmlattr'
depends = 'vim-textobj-user'

[[plugins]]
repo = 'thinca/vim-visualstar'

[[plugins]]
repo = 'vim-jp/autofmt'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'vim-jp/vital.vim'

[[plugins]]
repo = 'lambdalisue/vital-Whisky'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'kana/vim-fakeclip'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'kana/vim-textobj-jabraces'

[[plugins]]
repo = 'aiya000/lucariox.vim'

[[plugins]]
repo = 'machakann/vim-highlightedyank'

[[plugins]]
repo = 'andymass/vim-matchup'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'roxma/nvim-yarp'
