[[plugins]]
repo = 'basyura/TweetVim'
depends = [
    'open-browser.vim',
    'twibill.vim',
    'bitly.vim',
    'favstar-vim',
    'unite.vim',
]
on_cmd = [
    'TweetVimVersion',
    'TweetVimAddAccount',
    'TweetVimSwitchAccount',
    'TweetVimHomeTimeline',
    'TweetVimMentions',
    'TweetVimUserTimeline',
    'TweetVimListStatuses',
    'TweetVimSearch',
    'TweetVimSay',
    'TweetVimUserStream',
    'TweetVimCommandSay',
    'TweetVimCurrentLineSay',
    'TweetVimClearIcon',
]

[[plugins]]
repo = 'mattn/favstar-vim'
on_cmd = 'FavStar'

[[plugins]]
repo = 'basyura/twibill.vim'

[[plugins]]
repo = 'basyura/bitly.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'
depends = 'vimproc.vim'
on_cmd = 'QuickRun'
on_map = [
    '<Plug>(quickrun)',
    '<Plug>(quickrun-op)',
]

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'Shougo/vinarise.vim'
on_cmd = [
    'Vinarise',
    'VinariseDump',
]

[[plugins]]
repo = 'thinca/vim-themis'
on_ft = [
    'vim',
    'vimspec',
]

[[plugins]]
repo = 'kannokanno/previm'
on_ft = 'markdown',
on_cmd = 'PrevimOpen'

[[plugins]]
repo = 'mbbill/undotree'
on_cmd = [
    'UndotreeToggle',
    'UndotreeFocus',
    'UndotreeShow',
    'UndotreeHide',
]

[[plugins]]
repo = 'aiya000/adrone.vim'
on_cmd = [
    'AdroneHome',
    'AdroneSay',
    'AdroneVersion',
]

[[plugins]]
repo = 'LeafCage/vimhelpgenerator'
on_cmd = [
    'VimHelpGenerator',
    'VimHelpGeneratorVirtual',
    'HelpIntoMarkdown',
]

[[plugins]]
repo = 'rbtnn/vimconsole.vim'
on_cmd = [
    'VimConsoleLog',
    'VimConsoleOpen',
    'VimConsoleClose',
    'VimConsoleToggle',
    'VimConsoleClear',
    'VimConsoleRedraw',
]

[[plugins]]
repo = 'lambdalisue/vim-pager'
on_cmd = 'PAGER'

[[plugins]]
repo = 'lambdalisue/vim-manpager'
on_cmd = [
    'Man',
    'MANPAGER',
]

[[plugins]]
repo = 'thinca/vim-ft-clojure'
on_ft = [
    'clojure',
    'lisp',  # Please see ~/.vim/syntax/lisp.vim
]

[[plugins]]
repo = 'lambdalisue/vim-gista'
on_cmd = 'Gista'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'yomi322/neco-tweetvim'
on_source = 'TweetVim'

[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = 'scala'

[[plugins]]
repo = 'lambdalisue/gina.vim'
rev = '2e9de27914c3765c87dc28626af772ef6207375e'
on_cmd = 'Gina'
hook_source = 'call vimrc#dein#hook_source#gina()'

[[plugins]]
repo = 'udalov/kotlin-vim'
on_ft = 'kotlin'

[[plugins]]
repo = 'ianks/vim-tsx'
on_event = ['BufNewFile', 'BufRead']
on_ft = 'expand("%") =~# "\.tsx$"'

[[plugins]]
repo = 'vmchale/ghci-syntax'
on_ft = 'dot-ghci'

[[plugins]]
repo = 'aiya000/elm-vim'
rev = 'aiya000/use-command-bang'
on_ft = 'elm'
on_cmd = ['ElmFormat']

[[plugins]]
repo = 'aiya000/idris-vim'
rev = 'aiya000/can-be-disabled-keymappings'
on_ft = [
    'idris',
    'lidris',
]

# Now only for TweetVim
[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'TweetVim'
on_cmd = 'Unite'

[[plugins]]
repo = 'libclang-vim/libclang-vim'
build = 'make'
on_ft = ['c', 'cpp']

[[plugins]]
repo = 'libclang-vim/vim-textobj-clang'
depends = 'libclang-vim'
on_ft = ['c', 'cpp']

[[plugins]]
repo = 'haya14busa/incsearch.vim'
on_map = [
    '<Plug>(incsearch-forward)',
    '<Plug>(incsearch-backward)',
    '<Plug>(incsearch-stay)',
    '<Plug>(incsearch-nohl)',
    '<Plug>(incsearch-nohl0)',
    '<Plug>(incsearch-nohl-n)',
    '<Plug>(incsearch-nohl-N)',
    '<Plug>(incsearch-nohl-*)',
    '<Plug>(incsearch-nohl-#)',
    '<Plug>(incsearch-nohl-g*)',
    '<Plug>(incsearch-nohl-g#)',
]

[[plugins]]
repo = 'vim-scripts/alex.vim'
on_ft = 'alex'

[[plugins]]
repo = 'thinca/vim-textobj-between'
on_map = [
    '<Plug>(textobj-between-a)',
    '<Plug>(textobj-between-i)',
]

[[plugins]]
repo = 'rhysd/vim-operator-surround'
depends = 'vim-operator-user'
hook_source = 'call vimrc#dein#hook_source#operator_surround()'
on_map = [
    '<Plug>(operator-surround-append)',
    '<Plug>(operator-surround-delete)',
    '<Plug>(operator-surround-replace)',
]

[[plugins]]
repo = 'mattn/emmet-vim'
hook_source = 'call vimrc#dein#hook_source#emmet()'
on_ft = [
    'xml',
    'html',
    'markdown',
]

[[plugins]]
repo = 'aiya000/vim-review'
on_ft = 'review'

[[plugins]]
repo = 'aiya000/vim-fmap'
on_cmd = 'FNoreMap'
on_map = [
    '<Plug>(fmap-forward-f)',
    '<Plug>(fmap-backward-f)',
    '<Plug>(fmap-forward-t)',
    '<Plug>(fmap-backward-t)',
]

[[plugins]]
repo = 'Chiel92/vim-autoformat'
on_ft = [
    'haskell',
    'dhall',
    'scala',
    'java',
    'typescript',
]

[[plugins]]
repo = 'rhysd/vim-gfm-syntax'
on_ft = ['markdown']

[[plugins]]
repo = 'vmchale/dhall-vim'
on_ft = ['dhall']

[[plugins]]
repo = 'fszymanski/deoplete-emoji'
on_ft = [
    'markdown',
    'gitcommit',
]

[[plugins]]
repo = 'haya14busa/dein-command.vim'
on_cmd = 'Dein'

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
on_ft = [
    'haskell',
    'javascript',
    'typescript',
    'typescript.tsx',
]
depends = ['async.vim']

[[plugins]]
repo = 'prabirshrestha/async.vim'
on_source = 'vim-lsp'

[[plugins]]
repo = 'lighttiger2505/deoplete-vim-lsp'
on_source = 'vim-lsp'

[[plugins]]
repo = 'aiya000/vim-ghcid-quickfix'
on_ft = [
    'haskell',
    'happy',
    'alex',
]

[[plugins]]
repo = 'tyru/open-browser-github.vim'
on_cmd = [
    'OpenGithubFile',
    'OpenGithubIssue',
    'OpenGithubPullReq',
    'OpenGithubProject',
]

[[plugins]]
repo = 'gutenye/json5.vim'
on_ft = ['json5']

[[plugins]]
repo = 'itchyny/vim-haskell-sort-import'
on_ft = ['haskell']

[[plugins]]
repo = 'skanehira/translate.vim'
on_cmd = [
    'Translate',
    'AutoTranslateModeToggle',
    'AutoTranslateModeEnable',
    'AutoTranslateModeDisable',
]

[[plugins]]
repo = 'segeljakt/vim-silicon'
on_cmd = [
    'Silicon',
    'SiliconHighlight',
]

[[plugins]]
repo = 'aiya000/vim-webpage'
on_cmd = 'Webpage'

[[plugins]]
repo = 'tyru/operator-camelize.vim'
on_map = [
    '<Plug>(operator-camelize)',
    '<Plug>(operator-decamelize)',
    '<Plug>(operator-camelize-toggle)',
]

[[plugins]]
repo = 'AndrewRadev/quickpeek.vim'
on_ft = 'qf'

[[plugins]]
repo = 'aiya000/vim-quickrepl'
on_map = '<Plug>(quickrepl-open)'
on_cmd = 'QuickReplOpen'

[[plugins]]
repo = 'LeafCage/yankround.vim'
on_map = [
    '<Plug>(yankround-p)',
    '<Plug>(yankround-P)',
    '<Plug>(yankround-gp)',
    '<Plug>(yankround-gP)',
    '<Plug>(yankround-prev)',
    '<Plug>(yankround-next)',
]

[[plugins]]
repo = 'ap/vim-css-color'
on_ft = [
    'css',
    'scss',
    'sass',
    'html',
    'xml',
]

[[plugins]]
repo = 'delphinus/vim-firestore'
on_ft = 'firestore'
