[[plugins]]
repo = 'tyru/open-browser.vim'
rev  = '39e8064'

[[plugins]]
repo  = 'Shougo/vimproc.vim'
build = 'make'
if    = '!(g:vimrc["is_kaoriya"] && g:vimrc["is_windows"])'
rev   = '25cb83f'

[[plugins]]
repo = 'Shougo/vimshell.vim'
rev  = 'd0c5bef'

[[plugins]]
repo = 'supermomonga/vimshell-kawaii.vim'

[[plugins]]
repo = 'LeafCage/foldCC'

[[plugins]]
repo = 'kana/vim-submode'

[[plugins]]
repo = 'osyo-manga/vim-anzu'

[[plugins]]
repo = 'h1mesuke/vim-alignta'

[[plugins]]
repo = 'deris/vim-shot-f'

[[plugins]]
repo = 'tyru/vim-altercmd'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'aiya000/aho-bakaup.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
rev  = 'ddd01d0'

[[plugins]]
repo    = 'kana/vim-textobj-indent'
depends = 'vim-textobj-user'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
rev  = 'acae373'

[[plugins]]
repo = 'aiya000/vimshell-command-dehanai.vim'

[[plugins]]
repo    = 'osyo-manga/vim-textobj-from_regexp'
depends = 'vim-textobj-user'

[[plugins]]
repo    = 'whatyouhide/vim-textobj-xmlattr'
depends = 'vim-textobj-user'

[[plugins]]
repo = 'thinca/vim-visualstar'

[[plugins]]
repo = 'jonathanfilip/vim-lucius'

[[plugins]]
repo = 'aiya000/submode-window_move.vim'

[[plugins]]
repo = 'romainl/Apprentice'

[[plugins]]
repo = 'vim-jp/autofmt'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'vim-jp/vital.vim'

[[plugins]]
repo = 'lambdalisue/vital-Whisky'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'kana/vim-fakeclip'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'kana/vim-textobj-jabraces'

[[plugins]]
repo = 'aiya000/lucariox.vim'

[[plugins]]
repo = 'machakann/vim-highlightedyank'

[[plugins]]
repo = 'andymass/vim-matchup'

[[plugins]]
repo = 'ujihisa/unite-colorscheme'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'haya14busa/vim-migemo'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'Shougo/neco-syntax'
