[[plugins]]
repo = 'tyru/open-browser.vim'
rev = '39e80649c739151673373bbaf3a56d126531467b'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
if = '!g:vimrc.is_kaoriya && !g:vimrc.is_windows'

[[plugins]]
repo = 'LeafCage/foldCC'

[[plugins]]
repo = 'kana/vim-submode'

[[plugins]]
repo = 'osyo-manga/vim-anzu'

[[plugins]]
repo = 'deris/vim-shot-f'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'aiya000/aho-bakaup.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
rev = 'ed80ae8cee732d52eb841d509a95aca9c27ece7a'

[[plugins]]
repo = 'kana/vim-textobj-indent'
depends = 'vim-textobj-user'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
rev = 'd21aef18a1297e4a1a2a451ed03c515b4af0fd81'

[[plugins]]
repo = 'osyo-manga/vim-textobj-from_regexp'
depends = 'vim-textobj-user'

[[plugins]]
repo = 'whatyouhide/vim-textobj-xmlattr'
depends = 'vim-textobj-user'

[[plugins]]
repo = 'thinca/vim-visualstar'

[[plugins]]
repo = 'vim-jp/autofmt'

[[plugins]]
repo = 'dense-analysis/ale'

[[plugins]]
repo = 'vim-jp/vital.vim'

[[plugins]]
repo = 'lambdalisue/vital-Whisky'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
rev = 'db1ee51242b4b0c8ae3dee58be8cf7f82fb3e74a'

[[plugins]]
repo = 'kana/vim-textobj-jabraces'

[[plugins]]
repo = 'aiya000/lucariox.vim'

[[plugins]]
repo = 'machakann/vim-highlightedyank'

[[plugins]]
repo = 'andymass/vim-matchup'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'

[[plugins]]  # NOTE: This plugin cannot be lazy because (maybe) global functions of ./plugin is not cached.
repo = 'tyru/sync-term-cwd.vim'

[[plugins]]
repo = 'kana/vim-repeat'

[[plugins]]
repo = 'chip/vim-fat-finger'

[[plugins]]
repo = 'itchyny/vim-cursorword'

[[plugins]]
repo = 'justinmk/vim-dirvish'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
depends = ['async.vim']

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'lighttiger2505/deoplete-vim-lsp'

[[plugins]]
repo = 'rhysd/vim-lsp-ale'

[[plugins]]
repo = 'kana/vim-fakeclip'
if = 'g:vimrc.is_wsl || g:vimrc.is_wsl2'

[[plugins]]
repo = 'vim-scripts/Align'

[[plugins]]
repo = 'cohama/lexima.vim'
