#!/bin/bash
# Thanks http://qiita.com/uasi/items/a340bb487ec07caac799

# Must set user.name at local
if [[ -z $(git config --local user.name) ]] ; then
  echo 'fatal: user.name is not set locally'
  echo '       You must set user.name at local'
  exit 1
fi

# Must set user.email at local
if [[ -z $(git config --local user.email) ]] ; then
  echo 'fatal: user.email is not set locally'
  echo '       You must set user.email at local'
  exit 1
fi

user=$(git config user.name)
message="Will commit by **$user**"

echo "$message"
echo

if [[ $user == aiya000 ]] ; then
  effect=~/.dotfiles/bash-toys/assets/notification-3.mp3
else
  effect=~/.dotfiles/bash-toys/assets/notification-2.mp3
fi
~/.dotfiles/bash-toys/bin/notify Git "$message" "$effect"
