#!/bin/bash

function git-branch-name () {
  git branch 2> /dev/null | grep '\*\s.*' | awk '{print $2}'
}

function git-log-unpushed () {
  git log "$@" "origin/$(git-branch-name)..HEAD"
}

if [[ $MY_GIT_HOOK_DISABLE_FIXUP_CHECK -ne 1 ]] && git-log-unpushed --oneline | grep -E '^[a-z0-9]+ (\(.+\) )?fixup!' > /dev/null 2>&1 ; then
  echo 'You have to rebase fixup commits.'
  exit 1
fi

user=$(git config user.name)
gh auth switch --user "$user"

message="Will push by **$user**"
echo "$message"
echo

if [[ $user == aiya000 ]] ; then
  effect=~/.dotfiles/bash-toys/assets/notification-2.mp3
else
  effect=~/.dotfiles/bash-toys/assets/notification-3.mp3
fi
~/.dotfiles/bash-toys/bin/notify Git "$message" "$effect"
