#!/bin/sh
# Thanks http://qiita.com/uasi/items/a340bb487ec07caac799

# Must set user.name at local
if [ -z "`git config --local user.name`" ]; then
	echo 'fatal: user.name is not set locally'
	exit 1
fi

# Must set user.email at local
if [ -z "`git config --local user.email`" ]; then
	echo 'fatal: user.email is not set locally'
	exit 1
fi
