#!/bin/bash
# Thanks http://qiita.com/uasi/items/a340bb487ec07caac799

# Must set user.name at local
if [[ -z $(git config --local user.name) ]] ; then
  echo 'fatal: user.name is not set locally'
  echo '       You must set user.name at local'
  exit 1
fi

# Must set user.email at local
if [[ -z $(git config --local user.email) ]] ; then
  echo 'fatal: user.email is not set locally'
  echo '       You must set user.email at local'
  exit 1
fi

title='Git will commit by'
user=$(git config user.name)

echo "$title"
echo "$user"
echo

if [[ $DOTFILES_GIT_HOOKS_DENY_IF_THAT_USER != '' && $user != "$DOTFILES_GIT_HOOKS_DENY_IF_THAT_USER" ]] ; then
  echo "fatal: You can't commit as $user"
  echo "       Because DOTFILES_GIT_PUSH_DENY_IF_THAT_USER is set to $DOTFILES_GIT_PUSH_DENY_IF_THAT_USER"
  exit 1
fi

if [[ $user == aiya000 ]] ; then
  effect=~/.dotfiles/bash-toys/assets/notification-3.mp3
else
  effect=~/.dotfiles/bash-toys/assets/notification-2.mp3
fi
~/.dotfiles/bash-toys/bin/notify "$title" "$user" "$effect"
