#!/bin/bash

function git-branch-name () {
  git branch 2> /dev/null | grep '\*\s.*' | awk '{print $2}'
}

function git-log-unpushed () {
  git log "$@" "origin/$(git-branch-name)..HEAD"
}

if [[ $MY_GIT_HOOK_DISABLE_FIXUP_CHECK -ne 1 ]] && git-log-unpushed --oneline | grep -E '^[a-z0-9]+ (\(.+\) )?fixup!' > /dev/null 2>&1 ; then
  echo 'You have to rebase fixup commits.'
  exit 1
fi

title='Git will commit by'
user=$(git config user.name)

gh auth switch --user "$user"

echo "$title"
echo "$user"
echo

if [[ $DOTFILES_GIT_HOOKS_DENY_IF_THAT_USER != '' && $user != $DOTFILES_GIT_HOOKS_DENY_IF_THAT_USER ]] ; then
  echo "fatal: You can't commit as $user"
  echo "       Because DOTFILES_GIT_PUSH_DENY_IF_THAT_USER is set to $DOTFILES_GIT_PUSH_DENY_IF_THAT_USER"
  exit 1
fi

if [[ $user == aiya000 ]] ; then
  effect=~/.dotfiles/bash-toys/assets/notification-3.mp3
else
  effect=~/.dotfiles/bash-toys/assets/notification-2.mp3
fi
~/.dotfiles/bash-toys/bin/notify "$title" "$user" "$effect"
