#!/bin/bash

staged_files=()
while IFS='' read -r line ; do
  staged_files+=("$line") ;
done < <(git diff --cached --name-only)

mv "$1" ~/.backup/COMMIT_MSG
touch "$1"

echo '' >> "$1"
for staged_file in "${staged_files[@]}" ; do
  echo "# $staged_file" >> "$1"
done
echo '#' >> "$1"
cat ~/.backup/COMMIT_MSG >> "$1"

rm ~/.backup/COMMIT_MSG
