#!/bin/bash

tmp_path=~/.backup/COMMIT_EDITMSG

staged_files=()
while IFS='' read -r line ; do
  staged_files+=("$line") ;
done < <(git diff --cached --name-only)

commit_msg_lines=()
while IFS='' read -r line ; do
  commit_msg_lines+=("$line") ;
done < <(cat "$1")
commit_msg_lines_length=${#commit_msg_lines[@]}
commit_msg_lines_head=${commit_msg_lines[0]}
commit_msg_lines_tail=("${commit_msg_lines[@]:1:$commit_msg_lines_length}")

mv -i "$1" "$tmp_path"
touch "$1"

{
  echo "$commit_msg_lines_head"
  for staged_file in "${staged_files[@]}" ; do
    echo "# $staged_file"
  done
  echo '# - - -'
  for default_rest_lines in "${commit_msg_lines_tail[@]}" ; do
    echo "$default_rest_lines"
  done
} >> "$1"

rm "$tmp_path"
