
set shellslash

let $CYGVIMRC = '/cygwin/home/username/.dotfiles/.vimrc'
let $WINVIMRC = $MYVIMRC
let $MYVIMRC  = $CYGVIMRC
let $DESKTOP = 'C:/Users/username/Desktop'

command! WinVimConfig e $WINVIMRC


so $CYGVIMRC
cd $DESKTOP

