name: <`1:package-name`>
version: 0.1.0.0
category: Simple
author: aiya000
maintainer: aiya000 <aiya000.develop@gmail.com>
copyright: aiya000
license: MIT
homepage: https://github.com/aiya000/hs-<|1|>
description: <`2:subject`>
synopsis: <`3:what-do-this`>

ghc-options:
  - -Wall
  - -Wno-name-shadowing
  - -Wno-unused-do-bind
  - -Wno-orphans
  - -fprint-potential-instances
  - -fprint-explicit-kinds

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  <|1|>:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies: <|1|>

tests:
  doctest:
    main: DocTest.hs
    source-dirs:
      - test/doctest
      - src
    dependencies:
      - doctest
  tasty-test:
    main: Tasty.hs
    source-dirs:
      - test/tasty
      - src
    dependencies:
      - tasty
      - tasty-discover
