# This file contains default non-project-specific settings for 'stack', used
# in all projects.  For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/
#
templates:
  params:
    author-email: aiya000.develop@gmail.com
    author-name: aiya000
    category: Simple
    copyright: aiya000
    github-username: aiya000
