name: yi-config
version: 0.1.0.0
license: BSD3
maintainer: aiya000.develop@gmail.com
github: aiya000/dotfiles
category: Yi

ghc-options: -Wall -ferror-spans -threaded

flags:
  vty:
    description: Include the vty (CLI) frontend
    manual: True
    default: True
  pango:
    description: Include the pango (GUI) frontend
    manual: True
    default: True
  vim:
    description: Include the vim keymap
    manual: True
    default: True
  emacs:
    description: Include the emacs keymap
    manual: True
    default: True

dependencies:
    - base >= 4.8 && < 5
    - cmdargs
    - containers
    - extra
    - microlens-platform
    - mtl
    - oo-prototypes
    - yi-core
    - yi-keymap-emacs
    - yi-keymap-vim
    - yi-language
    - yi-misc-modes
    - yi-mode-haskell
    - yi-rope
    - transformers-base
    - unordered-containers
    - text

when:
  - condition: flag(vty)
    dependencies: yi-frontend-vty
    cpp-options: -DVTY
  - condition: flag(pango)
    dependencies: yi-frontend-pango
    cpp-options: -DPANGO
  - condition: flag(vim)
    dependencies: yi-keymap-vim
    cpp-options: -DVIM
  - condition: flag(emacs)
    dependencies: yi-keymap-emacs
    cpp-options: -DEMACS

executables:
    yi:
        main: Main.hs
        source-dirs: .
        other-modules:
            Yi.MyConfig.CmdOptions
          , Yi.MyConfig.Helper
