resolver: lts-7.1
packages:
- '.'
- location: './yi-origin'
  subdirs:
    - 'yi-core'
    - 'yi-frontend-vty'
    - 'yi-frontend-pango'
    - 'yi-keymap-vim'
    - 'yi-keymap-emacs'
    - 'yi-misc-modes'
    - 'yi-mode-haskell'
    - 'yi-mode-javascript'
extra-deps:
- optparse-applicative-0.13.0.0
